// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_API.Data;

namespace REST_API.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20191029074310_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("REST_API.Data.Models.Autors", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("autor");

                    b.HasKey("id");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("REST_API.Data.Models.Books", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("autorid");

                    b.Property<string>("desc");

                    b.Property<string>("name");

                    b.Property<bool>("stat");

                    b.HasKey("id");

                    b.HasIndex("autorid");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("REST_API.Data.Models.Books", b =>
                {
                    b.HasOne("REST_API.Data.Models.Autors", "autor")
                        .WithMany()
                        .HasForeignKey("autorid");
                });
#pragma warning restore 612, 618
        }
    }
}
